### ISSUE TITLE
Hardcoded NIST IP should be removed 

### ISSUE THREAD

**Issue by MDSchechtman** [dpelgrift/ISS-Tracker#3]
Using `129.6.15.28` directly as the timeserver produces inconsistent results after restarts. The first request over a given period of time will succeed but subsequent requests will never return until some timeout is reached.  

As per https://tf.nist.gov/tf-cgi/servers.cgi:

> Whether you connect to a server using the name or the IP address, it is a bad practice to “hard-code” a particular server name or address into a device so that these parameters cannot be changed by the end user if that becomes necessary at some future time.

> All users should ensure that their software NEVER queries a server more frequently than once every 4 seconds. Systems that exceed this rate will be refused service. In extreme cases, systems that exceed this limit may be considered as attempting a denial-of-service attack.

Oddly enough, I can produce this state by just power cycling once or twice.

The recommendation is to use `time.nist.gov`, so:

```
Udp.beginPacket("time.nist.gov", 123)
```

Which works fine for me.

**Comment by dpelgrift** [comment]
Thanks for letting me know. I've pushed an update to query time.nist.gov directly
